---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build tasks"
      - npm run lint
  build:
    commands:
      - echo "Building the application"
      - sam build
      - >
        sam package
        --output-template-file packaged-template.yaml
        --s3-bucket lambda-deployment-bucket-amge-serverless
  post_build:
    commands:
      - echo "Deploying application"
      - |
        sam deploy \
        --template-file packaged-template.yaml \
        --stack-name my-lambda-stack \
        --capabilities \
        CAPABILITY_NAMED_IAM \
        CAPABILITY_AUTO_EXPAND \
        CAPABILITY_IAM \
        --region eu-west-1 \
        --s3-bucket lambda-deployment-bucket-amge-serverless \
        --confirm-changeset \
        --no-fail-on-empty-changeset \
        --debug

artifacts:
  files:
    - packaged-template.yaml
  discard-paths: true
