
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build tasks"
      - npm run lint
  build:
    commands:
      - echo "Building the application"
      - sam build
      - echo "Packaging CloudFormation template"
      - sam package --output-template-file packaged-template.yaml --s3-bucket lambda-deployment-bucket-amge-serverless      
  post_build:
    commands:
      - echo "Running post-build tasks"
      - npm test
artifacts:
  files:
    - packaged-template.yaml
  discard-paths: yes
