# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aindriu
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-api-gateway-crud-rest-api
service: aws-api-gateway-crud-rest-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1  
  stage: ${opt:stage, 'dev'}  # Allows specifying the stage (e.g., dev, prod)
  profile: serverless-deployer
  deploymentBucket:
    name: amge-deployment-bucket
  environment:
    ITEMS_TABLE: !Ref ItemsTable
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: "arn:aws:dynamodb:eu-west-1:869935109465:table/ItemsTable"

functions:
  create:
    handler: src/handlers/create.handler
    events:
      - http:
          path: items
          method: post

  read:
    handler: src/handlers/read.handler
    events:
      - http:
          path: items/{id}
          method: get

  update:
    handler: src/handlers/update.handler
    events:
      - http:
          path: items/{id}
          method: put

  delete:
    handler: src/handlers/delete.handler
    events:
      - http:
          path: items/{id}
          method: delete

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

