org: aindriu
app: aws-api-gateway-crud-rest-api
service: aws-api-gateway-crud-rest-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1  
  stage: ${opt:stage, 'dev'}
  profile: serverless-deployer
  deploymentBucket:
    name: amge-deployment-bucket
  environment:
    ITEMS_TABLE: !Ref ItemsTable  # Correct way to reference the table name
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource: !GetAtt ItemsTable.Arn  # Correct way to reference the table ARN

functions:
  create:
    handler: src/handlers/create.handler
    environment:
      ITEMS_TABLE: !Ref ItemsTable  # Correct way to reference the table name
    events:
      - http:
          path: items
          method: post

  read:
    handler: src/handlers/read.handler
    environment:
      ITEMS_TABLE: !Ref ItemsTable  # Correct way to reference the table name
    events:
      - http:
          path: items/{id}
          method: get

  update:
    handler: src/handlers/update.handler
    environment:
      ITEMS_TABLE: !Ref ItemsTable  # Correct way to reference the table name
    events:
      - http:
          path: items/{id}
          method: put

  delete:
    handler: src/handlers/delete.handler
    environment:
      ITEMS_TABLE: !Ref ItemsTable  # Correct way to reference the table name
    events:
      - http:
          path: items/{id}
          method: delete

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemsTable  # You can set a fixed table name, or remove this if CloudFormation manages it automatically
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - tests/**           
    - .git/**           

custom:
  esbuild:
    bundle: true           
    minify: true          
    exclude: ['aws-sdk'] 
    target: "node18"    
    define:
      "require.resolve": undefined

